version: "3.7"

services:
  rstudio:
    labels:
      - Author="Lucas Eliaquim"
    image: rocker/rstudio
    env_file:
      - .env
    ports:
      - "8787:8787"
    volumes:
      - ./:/home/rstudio
